// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_NgingOauthApp = factory.Slicex[*NgingOauthApp]

func NewNgingOauthApp(ctx echo.Context) *NgingOauthApp {
	m := &NgingOauthApp{}
	m.SetContext(ctx)
	return m
}

// NgingOauthApp oauth2应用
type NgingOauthApp struct {
	base    factory.Base
	objects []*NgingOauthApp

	Id              uint64 `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	AppId           string `db:"app_id" bson:"app_id" comment:"App ID" json:"app_id" xml:"app_id"`
	AppSecret       string `db:"app_secret" bson:"app_secret" comment:"App 密钥" json:"-" xml:"-"`
	SiteName        string `db:"site_name" bson:"site_name" comment:"外部站点名称" json:"site_name" xml:"site_name"`
	SiteDescription string `db:"site_description" bson:"site_description" comment:"外部站点说明" json:"site_description" xml:"site_description"`
	SiteDomains     string `db:"site_domains" bson:"site_domains" comment:"允许的外部站点域名(多个用\",\"分隔;留空为不限制)" json:"site_domains" xml:"site_domains"`
	Scopes          string `db:"scopes" bson:"scopes" comment:"授权业务(多个用\",\"分隔)" json:"scopes" xml:"scopes"`
	GroupId         uint   `db:"group_id" bson:"group_id" comment:"分组" json:"group_id" xml:"group_id"`
	Disabled        string `db:"disabled" bson:"disabled" comment:"是否(Y/N)禁用" json:"disabled" xml:"disabled"`
	Created         uint   `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created" form_decoder:"time2unix" form_encoder:"unix2time"`
	Updated         uint   `db:"updated" bson:"updated" comment:"更新时间" json:"updated" xml:"updated" form_decoder:"time2unix" form_encoder:"unix2time"`
}

// - base function

func (a *NgingOauthApp) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *NgingOauthApp) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *NgingOauthApp) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *NgingOauthApp) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *NgingOauthApp) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *NgingOauthApp) Context() echo.Context {
	return a.base.Context()
}

func (a *NgingOauthApp) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *NgingOauthApp) ConnID() int {
	return a.base.ConnID()
}

func (a *NgingOauthApp) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *NgingOauthApp) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *NgingOauthApp) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *NgingOauthApp) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *NgingOauthApp) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *NgingOauthApp) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *NgingOauthApp) Objects() []*NgingOauthApp {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *NgingOauthApp) XObjects() Slice_NgingOauthApp {
	return Slice_NgingOauthApp(a.Objects())
}

func (a *NgingOauthApp) NewObjects() factory.Ranger {
	return &Slice_NgingOauthApp{}
}

func (a *NgingOauthApp) InitObjects() *[]*NgingOauthApp {
	a.objects = []*NgingOauthApp{}
	return &a.objects
}

func (a *NgingOauthApp) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *NgingOauthApp) Short_() string {
	return "nging_oauth_app"
}

func (a *NgingOauthApp) Struct_() string {
	return "NgingOauthApp"
}

func (a *NgingOauthApp) Name_() string {
	b := a
	if b == nil {
		b = &NgingOauthApp{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *NgingOauthApp) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *NgingOauthApp) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *NgingOauthApp) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *NgingOauthApp) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*NgingOauthApp:
			err = a.base.FireReaded(a, queryParam, Slice_NgingOauthApp(*v))
		case []*NgingOauthApp:
			err = a.base.FireReaded(a, queryParam, Slice_NgingOauthApp(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *NgingOauthApp) GroupBy(keyField string, inputRows ...[]*NgingOauthApp) map[string][]*NgingOauthApp {
	var rows Slice_NgingOauthApp
	if len(inputRows) > 0 {
		rows = Slice_NgingOauthApp(inputRows[0])
	} else {
		rows = Slice_NgingOauthApp(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *NgingOauthApp) KeyBy(keyField string, inputRows ...[]*NgingOauthApp) map[string]*NgingOauthApp {
	var rows Slice_NgingOauthApp
	if len(inputRows) > 0 {
		rows = Slice_NgingOauthApp(inputRows[0])
	} else {
		rows = Slice_NgingOauthApp(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *NgingOauthApp) AsKV(keyField string, valueField string, inputRows ...[]*NgingOauthApp) param.Store {
	var rows Slice_NgingOauthApp
	if len(inputRows) > 0 {
		rows = Slice_NgingOauthApp(inputRows[0])
	} else {
		rows = Slice_NgingOauthApp(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *NgingOauthApp) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*NgingOauthApp:
			err = a.base.FireReaded(a, queryParam, Slice_NgingOauthApp(*v))
		case []*NgingOauthApp:
			err = a.base.FireReaded(a, queryParam, Slice_NgingOauthApp(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *NgingOauthApp) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *NgingOauthApp) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *NgingOauthApp) GetDiffColumns(old *NgingOauthApp) (changedCols []interface{}) {

	if old.Id != a.Id {
		changedCols = append(changedCols, `id`)
	}

	if old.AppId != a.AppId {
		changedCols = append(changedCols, `app_id`)
	}

	if old.AppSecret != a.AppSecret {
		changedCols = append(changedCols, `app_secret`)
	}

	if old.SiteName != a.SiteName {
		changedCols = append(changedCols, `site_name`)
	}

	if old.SiteDescription != a.SiteDescription {
		changedCols = append(changedCols, `site_description`)
	}

	if old.SiteDomains != a.SiteDomains {
		changedCols = append(changedCols, `site_domains`)
	}

	if old.Scopes != a.Scopes {
		changedCols = append(changedCols, `scopes`)
	}

	if old.GroupId != a.GroupId {
		changedCols = append(changedCols, `group_id`)
	}

	if old.Disabled != a.Disabled {
		changedCols = append(changedCols, `disabled`)
	}

	if old.Created != a.Created {
		changedCols = append(changedCols, `created`)
	}

	if old.Updated != a.Updated {
		changedCols = append(changedCols, `updated`)
	}

	return
}

func (a *NgingOauthApp) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *NgingOauthApp) Save(old *NgingOauthApp, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if old == nil {
		old = NewNgingOauthApp(a.Context())
		old.CtxFrom(a)
		if err = old.Get(nil, args...); err != nil {
			return
		}
	}
	changedCols := a.GetDiffColumns(old)
	if len(changedCols) == 0 {
		return
	}
	mw := func(r db.Result) db.Result {
		return r.Select(changedCols...).Limit(1)
	}
	return a.Updatex(mw, args...)
}

func (a *NgingOauthApp) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *NgingOauthApp) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *NgingOauthApp) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *NgingOauthApp) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *NgingOauthApp) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *NgingOauthApp) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *NgingOauthApp) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *NgingOauthApp) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		a.Updated = uint(time.Now().Unix())
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint64); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint64(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *NgingOauthApp) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *NgingOauthApp) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *NgingOauthApp) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *NgingOauthApp) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *NgingOauthApp) Reset() *NgingOauthApp {
	a.Id = 0
	a.AppId = ``
	a.AppSecret = ``
	a.SiteName = ``
	a.SiteDescription = ``
	a.SiteDomains = ``
	a.Scopes = ``
	a.GroupId = 0
	a.Disabled = ``
	a.Created = 0
	a.Updated = 0
	return a
}

func (a *NgingOauthApp) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["AppId"] = a.AppId
		r["AppSecret"] = a.AppSecret
		r["SiteName"] = a.SiteName
		r["SiteDescription"] = a.SiteDescription
		r["SiteDomains"] = a.SiteDomains
		r["Scopes"] = a.Scopes
		r["GroupId"] = a.GroupId
		r["Disabled"] = a.Disabled
		r["Created"] = a.Created
		r["Updated"] = a.Updated
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "AppId":
			r["AppId"] = a.AppId
		case "AppSecret":
			r["AppSecret"] = a.AppSecret
		case "SiteName":
			r["SiteName"] = a.SiteName
		case "SiteDescription":
			r["SiteDescription"] = a.SiteDescription
		case "SiteDomains":
			r["SiteDomains"] = a.SiteDomains
		case "Scopes":
			r["Scopes"] = a.Scopes
		case "GroupId":
			r["GroupId"] = a.GroupId
		case "Disabled":
			r["Disabled"] = a.Disabled
		case "Created":
			r["Created"] = a.Created
		case "Updated":
			r["Updated"] = a.Updated
		}
	}
	return r
}

func (a *NgingOauthApp) Clone() *NgingOauthApp {
	cloned := NgingOauthApp{Id: a.Id, AppId: a.AppId, AppSecret: a.AppSecret, SiteName: a.SiteName, SiteDescription: a.SiteDescription, SiteDomains: a.SiteDomains, Scopes: a.Scopes, GroupId: a.GroupId, Disabled: a.Disabled, Created: a.Created, Updated: a.Updated}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *NgingOauthApp) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "id":
			a.Id = param.AsUint64(value)
		case "app_id":
			a.AppId = param.AsString(value)
		case "app_secret":
			a.AppSecret = param.AsString(value)
		case "site_name":
			a.SiteName = param.AsString(value)
		case "site_description":
			a.SiteDescription = param.AsString(value)
		case "site_domains":
			a.SiteDomains = param.AsString(value)
		case "scopes":
			a.Scopes = param.AsString(value)
		case "group_id":
			a.GroupId = param.AsUint(value)
		case "disabled":
			a.Disabled = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		case "updated":
			a.Updated = param.AsUint(value)
		}
	}
}

func (a *NgingOauthApp) GetField(field string) interface{} {
	switch field {
	case "Id":
		return a.Id
	case "AppId":
		return a.AppId
	case "AppSecret":
		return a.AppSecret
	case "SiteName":
		return a.SiteName
	case "SiteDescription":
		return a.SiteDescription
	case "SiteDomains":
		return a.SiteDomains
	case "Scopes":
		return a.Scopes
	case "GroupId":
		return a.GroupId
	case "Disabled":
		return a.Disabled
	case "Created":
		return a.Created
	case "Updated":
		return a.Updated
	default:
		return nil
	}
}

func (a *NgingOauthApp) GetAllFieldNames() []string {
	return []string{
		"Id",
		"AppId",
		"AppSecret",
		"SiteName",
		"SiteDescription",
		"SiteDomains",
		"Scopes",
		"GroupId",
		"Disabled",
		"Created",
		"Updated",
	}
}

func (a *NgingOauthApp) HasField(field string) bool {
	switch field {
	case "Id":
		return true
	case "AppId":
		return true
	case "AppSecret":
		return true
	case "SiteName":
		return true
	case "SiteDescription":
		return true
	case "SiteDomains":
		return true
	case "Scopes":
		return true
	case "GroupId":
		return true
	case "Disabled":
		return true
	case "Created":
		return true
	case "Updated":
		return true
	default:
		return false
	}
}

func (a *NgingOauthApp) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint64(vv)
		case "AppId":
			a.AppId = param.AsString(vv)
		case "AppSecret":
			a.AppSecret = param.AsString(vv)
		case "SiteName":
			a.SiteName = param.AsString(vv)
		case "SiteDescription":
			a.SiteDescription = param.AsString(vv)
		case "SiteDomains":
			a.SiteDomains = param.AsString(vv)
		case "Scopes":
			a.Scopes = param.AsString(vv)
		case "GroupId":
			a.GroupId = param.AsUint(vv)
		case "Disabled":
			a.Disabled = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Updated":
			a.Updated = param.AsUint(vv)
		}
	}
}

func (a *NgingOauthApp) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["app_id"] = a.AppId
		r["app_secret"] = a.AppSecret
		r["site_name"] = a.SiteName
		r["site_description"] = a.SiteDescription
		r["site_domains"] = a.SiteDomains
		r["scopes"] = a.Scopes
		r["group_id"] = a.GroupId
		r["disabled"] = a.Disabled
		r["created"] = a.Created
		r["updated"] = a.Updated
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "app_id":
			r["app_id"] = a.AppId
		case "app_secret":
			r["app_secret"] = a.AppSecret
		case "site_name":
			r["site_name"] = a.SiteName
		case "site_description":
			r["site_description"] = a.SiteDescription
		case "site_domains":
			r["site_domains"] = a.SiteDomains
		case "scopes":
			r["scopes"] = a.Scopes
		case "group_id":
			r["group_id"] = a.GroupId
		case "disabled":
			r["disabled"] = a.Disabled
		case "created":
			r["created"] = a.Created
		case "updated":
			r["updated"] = a.Updated
		}
	}
	return r
}

func (a *NgingOauthApp) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *NgingOauthApp) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *NgingOauthApp) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *NgingOauthApp) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *NgingOauthApp) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *NgingOauthApp) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *NgingOauthApp) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
