// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_NgingUserRolePermission = factory.Slicex[*NgingUserRolePermission]

func NewNgingUserRolePermission(ctx echo.Context) *NgingUserRolePermission {
	m := &NgingUserRolePermission{}
	m.SetContext(ctx)
	return m
}

// NgingUserRolePermission
type NgingUserRolePermission struct {
	base    factory.Base
	objects []*NgingUserRolePermission

	RoleId     uint   `db:"role_id,pk" bson:"role_id" comment:"角色ID" json:"role_id" xml:"role_id"`
	Type       string `db:"type,pk" bson:"type" comment:"权限类型" json:"type" xml:"type"`
	Permission string `db:"permission" bson:"permission" comment:"权限值" json:"permission" xml:"permission"`
}

// - base function

func (a *NgingUserRolePermission) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *NgingUserRolePermission) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *NgingUserRolePermission) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *NgingUserRolePermission) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *NgingUserRolePermission) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *NgingUserRolePermission) Context() echo.Context {
	return a.base.Context()
}

func (a *NgingUserRolePermission) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *NgingUserRolePermission) ConnID() int {
	return a.base.ConnID()
}

func (a *NgingUserRolePermission) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *NgingUserRolePermission) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *NgingUserRolePermission) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *NgingUserRolePermission) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *NgingUserRolePermission) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *NgingUserRolePermission) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *NgingUserRolePermission) Objects() []*NgingUserRolePermission {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *NgingUserRolePermission) XObjects() Slice_NgingUserRolePermission {
	return Slice_NgingUserRolePermission(a.Objects())
}

func (a *NgingUserRolePermission) NewObjects() factory.Ranger {
	return &Slice_NgingUserRolePermission{}
}

func (a *NgingUserRolePermission) InitObjects() *[]*NgingUserRolePermission {
	a.objects = []*NgingUserRolePermission{}
	return &a.objects
}

func (a *NgingUserRolePermission) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *NgingUserRolePermission) Short_() string {
	return "nging_user_role_permission"
}

func (a *NgingUserRolePermission) Struct_() string {
	return "NgingUserRolePermission"
}

func (a *NgingUserRolePermission) Name_() string {
	b := a
	if b == nil {
		b = &NgingUserRolePermission{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *NgingUserRolePermission) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *NgingUserRolePermission) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *NgingUserRolePermission) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *NgingUserRolePermission) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*NgingUserRolePermission:
			err = a.base.FireReaded(a, queryParam, Slice_NgingUserRolePermission(*v))
		case []*NgingUserRolePermission:
			err = a.base.FireReaded(a, queryParam, Slice_NgingUserRolePermission(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *NgingUserRolePermission) GroupBy(keyField string, inputRows ...[]*NgingUserRolePermission) map[string][]*NgingUserRolePermission {
	var rows Slice_NgingUserRolePermission
	if len(inputRows) > 0 {
		rows = Slice_NgingUserRolePermission(inputRows[0])
	} else {
		rows = Slice_NgingUserRolePermission(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *NgingUserRolePermission) KeyBy(keyField string, inputRows ...[]*NgingUserRolePermission) map[string]*NgingUserRolePermission {
	var rows Slice_NgingUserRolePermission
	if len(inputRows) > 0 {
		rows = Slice_NgingUserRolePermission(inputRows[0])
	} else {
		rows = Slice_NgingUserRolePermission(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *NgingUserRolePermission) AsKV(keyField string, valueField string, inputRows ...[]*NgingUserRolePermission) param.Store {
	var rows Slice_NgingUserRolePermission
	if len(inputRows) > 0 {
		rows = Slice_NgingUserRolePermission(inputRows[0])
	} else {
		rows = Slice_NgingUserRolePermission(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *NgingUserRolePermission) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*NgingUserRolePermission:
			err = a.base.FireReaded(a, queryParam, Slice_NgingUserRolePermission(*v))
		case []*NgingUserRolePermission:
			err = a.base.FireReaded(a, queryParam, Slice_NgingUserRolePermission(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *NgingUserRolePermission) Insert() (pk interface{}, err error) {

	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()

	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *NgingUserRolePermission) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *NgingUserRolePermission) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *NgingUserRolePermission) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *NgingUserRolePermission) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *NgingUserRolePermission) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *NgingUserRolePermission) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *NgingUserRolePermission) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *NgingUserRolePermission) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *NgingUserRolePermission) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *NgingUserRolePermission) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})

	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *NgingUserRolePermission) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *NgingUserRolePermission) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *NgingUserRolePermission) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *NgingUserRolePermission) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *NgingUserRolePermission) Reset() *NgingUserRolePermission {
	a.RoleId = 0
	a.Type = ``
	a.Permission = ``
	return a
}

func (a *NgingUserRolePermission) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["RoleId"] = a.RoleId
		r["Type"] = a.Type
		r["Permission"] = a.Permission
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "RoleId":
			r["RoleId"] = a.RoleId
		case "Type":
			r["Type"] = a.Type
		case "Permission":
			r["Permission"] = a.Permission
		}
	}
	return r
}

func (a *NgingUserRolePermission) Clone() *NgingUserRolePermission {
	cloned := NgingUserRolePermission{RoleId: a.RoleId, Type: a.Type, Permission: a.Permission}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *NgingUserRolePermission) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "role_id":
			a.RoleId = param.AsUint(value)
		case "type":
			a.Type = param.AsString(value)
		case "permission":
			a.Permission = param.AsString(value)
		}
	}
}

func (a *NgingUserRolePermission) GetField(field string) interface{} {
	switch field {
	case "RoleId":
		return a.RoleId
	case "Type":
		return a.Type
	case "Permission":
		return a.Permission
	default:
		return nil
	}
}

func (a *NgingUserRolePermission) GetAllFieldNames() []string {
	return []string{
		"RoleId",
		"Type",
		"Permission",
	}
}

func (a *NgingUserRolePermission) HasField(field string) bool {
	switch field {
	case "RoleId":
		return true
	case "Type":
		return true
	case "Permission":
		return true
	default:
		return false
	}
}

func (a *NgingUserRolePermission) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "RoleId":
			a.RoleId = param.AsUint(vv)
		case "Type":
			a.Type = param.AsString(vv)
		case "Permission":
			a.Permission = param.AsString(vv)
		}
	}
}

func (a *NgingUserRolePermission) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["role_id"] = a.RoleId
		r["type"] = a.Type
		r["permission"] = a.Permission
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "role_id":
			r["role_id"] = a.RoleId
		case "type":
			r["type"] = a.Type
		case "permission":
			r["permission"] = a.Permission
		}
	}
	return r
}

func (a *NgingUserRolePermission) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *NgingUserRolePermission) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *NgingUserRolePermission) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *NgingUserRolePermission) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *NgingUserRolePermission) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *NgingUserRolePermission) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *NgingUserRolePermission) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
