// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_NgingCodeInvitation = factory.Slicex[*NgingCodeInvitation]

func NewNgingCodeInvitation(ctx echo.Context) *NgingCodeInvitation {
	m := &NgingCodeInvitation{}
	m.SetContext(ctx)
	return m
}

// NgingCodeInvitation 邀请码
type NgingCodeInvitation struct {
	base    factory.Base
	objects []*NgingCodeInvitation

	Id       uint   `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	Uid      uint   `db:"uid" bson:"uid" comment:"创建者" json:"uid" xml:"uid"`
	RecvUid  uint   `db:"recv_uid" bson:"recv_uid" comment:"使用者" json:"recv_uid" xml:"recv_uid"`
	Code     string `db:"code" bson:"code" comment:"邀请码" json:"code" xml:"code"`
	Created  uint   `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created" form_decoder:"time2unix" form_encoder:"unix2time"`
	Used     uint   `db:"used" bson:"used" comment:"使用时间" json:"used" xml:"used"`
	Start    uint   `db:"start" bson:"start" comment:"有效时间" json:"start" xml:"start"`
	End      uint   `db:"end" bson:"end" comment:"失效时间" json:"end" xml:"end"`
	Disabled string `db:"disabled" bson:"disabled" comment:"是否禁用" json:"disabled" xml:"disabled"`
	RoleIds  string `db:"role_ids" bson:"role_ids" comment:"注册为角色(多个用“,”分隔开)" json:"role_ids" xml:"role_ids"`
}

// - base function

func (a *NgingCodeInvitation) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *NgingCodeInvitation) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *NgingCodeInvitation) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *NgingCodeInvitation) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *NgingCodeInvitation) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *NgingCodeInvitation) Context() echo.Context {
	return a.base.Context()
}

func (a *NgingCodeInvitation) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *NgingCodeInvitation) ConnID() int {
	return a.base.ConnID()
}

func (a *NgingCodeInvitation) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *NgingCodeInvitation) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *NgingCodeInvitation) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *NgingCodeInvitation) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *NgingCodeInvitation) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *NgingCodeInvitation) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *NgingCodeInvitation) Objects() []*NgingCodeInvitation {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *NgingCodeInvitation) XObjects() Slice_NgingCodeInvitation {
	return Slice_NgingCodeInvitation(a.Objects())
}

func (a *NgingCodeInvitation) NewObjects() factory.Ranger {
	return &Slice_NgingCodeInvitation{}
}

func (a *NgingCodeInvitation) InitObjects() *[]*NgingCodeInvitation {
	a.objects = []*NgingCodeInvitation{}
	return &a.objects
}

func (a *NgingCodeInvitation) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *NgingCodeInvitation) Short_() string {
	return "nging_code_invitation"
}

func (a *NgingCodeInvitation) Struct_() string {
	return "NgingCodeInvitation"
}

func (a *NgingCodeInvitation) Name_() string {
	b := a
	if b == nil {
		b = &NgingCodeInvitation{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *NgingCodeInvitation) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *NgingCodeInvitation) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *NgingCodeInvitation) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *NgingCodeInvitation) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*NgingCodeInvitation:
			err = a.base.FireReaded(a, queryParam, Slice_NgingCodeInvitation(*v))
		case []*NgingCodeInvitation:
			err = a.base.FireReaded(a, queryParam, Slice_NgingCodeInvitation(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *NgingCodeInvitation) GroupBy(keyField string, inputRows ...[]*NgingCodeInvitation) map[string][]*NgingCodeInvitation {
	var rows Slice_NgingCodeInvitation
	if len(inputRows) > 0 {
		rows = Slice_NgingCodeInvitation(inputRows[0])
	} else {
		rows = Slice_NgingCodeInvitation(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *NgingCodeInvitation) KeyBy(keyField string, inputRows ...[]*NgingCodeInvitation) map[string]*NgingCodeInvitation {
	var rows Slice_NgingCodeInvitation
	if len(inputRows) > 0 {
		rows = Slice_NgingCodeInvitation(inputRows[0])
	} else {
		rows = Slice_NgingCodeInvitation(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *NgingCodeInvitation) AsKV(keyField string, valueField string, inputRows ...[]*NgingCodeInvitation) param.Store {
	var rows Slice_NgingCodeInvitation
	if len(inputRows) > 0 {
		rows = Slice_NgingCodeInvitation(inputRows[0])
	} else {
		rows = Slice_NgingCodeInvitation(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *NgingCodeInvitation) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*NgingCodeInvitation:
			err = a.base.FireReaded(a, queryParam, Slice_NgingCodeInvitation(*v))
		case []*NgingCodeInvitation:
			err = a.base.FireReaded(a, queryParam, Slice_NgingCodeInvitation(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *NgingCodeInvitation) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *NgingCodeInvitation) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *NgingCodeInvitation) GetDiffColumns(old *NgingCodeInvitation) (changedCols []interface{}) {

	if old.Id != a.Id {
		changedCols = append(changedCols, `id`)
	}

	if old.Uid != a.Uid {
		changedCols = append(changedCols, `uid`)
	}

	if old.RecvUid != a.RecvUid {
		changedCols = append(changedCols, `recv_uid`)
	}

	if old.Code != a.Code {
		changedCols = append(changedCols, `code`)
	}

	if old.Created != a.Created {
		changedCols = append(changedCols, `created`)
	}

	if old.Used != a.Used {
		changedCols = append(changedCols, `used`)
	}

	if old.Start != a.Start {
		changedCols = append(changedCols, `start`)
	}

	if old.End != a.End {
		changedCols = append(changedCols, `end`)
	}

	if old.Disabled != a.Disabled {
		changedCols = append(changedCols, `disabled`)
	}

	if old.RoleIds != a.RoleIds {
		changedCols = append(changedCols, `role_ids`)
	}

	return
}

func (a *NgingCodeInvitation) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *NgingCodeInvitation) Save(old *NgingCodeInvitation, args ...interface{}) (affected int64, err error) {

	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if old == nil {
		old = NewNgingCodeInvitation(a.Context())
		old.CtxFrom(a)
		if err = old.Get(nil, args...); err != nil {
			return
		}
	}
	changedCols := a.GetDiffColumns(old)
	if len(changedCols) == 0 {
		return
	}
	mw := func(r db.Result) db.Result {
		return r.Select(changedCols...).Limit(1)
	}
	return a.Updatex(mw, args...)
}

func (a *NgingCodeInvitation) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {

	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *NgingCodeInvitation) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {

	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *NgingCodeInvitation) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *NgingCodeInvitation) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *NgingCodeInvitation) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *NgingCodeInvitation) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *NgingCodeInvitation) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *NgingCodeInvitation) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *NgingCodeInvitation) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *NgingCodeInvitation) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *NgingCodeInvitation) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *NgingCodeInvitation) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *NgingCodeInvitation) Reset() *NgingCodeInvitation {
	a.Id = 0
	a.Uid = 0
	a.RecvUid = 0
	a.Code = ``
	a.Created = 0
	a.Used = 0
	a.Start = 0
	a.End = 0
	a.Disabled = ``
	a.RoleIds = ``
	return a
}

func (a *NgingCodeInvitation) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["Uid"] = a.Uid
		r["RecvUid"] = a.RecvUid
		r["Code"] = a.Code
		r["Created"] = a.Created
		r["Used"] = a.Used
		r["Start"] = a.Start
		r["End"] = a.End
		r["Disabled"] = a.Disabled
		r["RoleIds"] = a.RoleIds
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "Uid":
			r["Uid"] = a.Uid
		case "RecvUid":
			r["RecvUid"] = a.RecvUid
		case "Code":
			r["Code"] = a.Code
		case "Created":
			r["Created"] = a.Created
		case "Used":
			r["Used"] = a.Used
		case "Start":
			r["Start"] = a.Start
		case "End":
			r["End"] = a.End
		case "Disabled":
			r["Disabled"] = a.Disabled
		case "RoleIds":
			r["RoleIds"] = a.RoleIds
		}
	}
	return r
}

func (a *NgingCodeInvitation) Clone() *NgingCodeInvitation {
	cloned := NgingCodeInvitation{Id: a.Id, Uid: a.Uid, RecvUid: a.RecvUid, Code: a.Code, Created: a.Created, Used: a.Used, Start: a.Start, End: a.End, Disabled: a.Disabled, RoleIds: a.RoleIds}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *NgingCodeInvitation) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "id":
			a.Id = param.AsUint(value)
		case "uid":
			a.Uid = param.AsUint(value)
		case "recv_uid":
			a.RecvUid = param.AsUint(value)
		case "code":
			a.Code = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		case "used":
			a.Used = param.AsUint(value)
		case "start":
			a.Start = param.AsUint(value)
		case "end":
			a.End = param.AsUint(value)
		case "disabled":
			a.Disabled = param.AsString(value)
		case "role_ids":
			a.RoleIds = param.AsString(value)
		}
	}
}

func (a *NgingCodeInvitation) GetField(field string) interface{} {
	switch field {
	case "Id":
		return a.Id
	case "Uid":
		return a.Uid
	case "RecvUid":
		return a.RecvUid
	case "Code":
		return a.Code
	case "Created":
		return a.Created
	case "Used":
		return a.Used
	case "Start":
		return a.Start
	case "End":
		return a.End
	case "Disabled":
		return a.Disabled
	case "RoleIds":
		return a.RoleIds
	default:
		return nil
	}
}

func (a *NgingCodeInvitation) GetAllFieldNames() []string {
	return []string{
		"Id",
		"Uid",
		"RecvUid",
		"Code",
		"Created",
		"Used",
		"Start",
		"End",
		"Disabled",
		"RoleIds",
	}
}

func (a *NgingCodeInvitation) HasField(field string) bool {
	switch field {
	case "Id":
		return true
	case "Uid":
		return true
	case "RecvUid":
		return true
	case "Code":
		return true
	case "Created":
		return true
	case "Used":
		return true
	case "Start":
		return true
	case "End":
		return true
	case "Disabled":
		return true
	case "RoleIds":
		return true
	default:
		return false
	}
}

func (a *NgingCodeInvitation) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint(vv)
		case "Uid":
			a.Uid = param.AsUint(vv)
		case "RecvUid":
			a.RecvUid = param.AsUint(vv)
		case "Code":
			a.Code = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Used":
			a.Used = param.AsUint(vv)
		case "Start":
			a.Start = param.AsUint(vv)
		case "End":
			a.End = param.AsUint(vv)
		case "Disabled":
			a.Disabled = param.AsString(vv)
		case "RoleIds":
			a.RoleIds = param.AsString(vv)
		}
	}
}

func (a *NgingCodeInvitation) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["uid"] = a.Uid
		r["recv_uid"] = a.RecvUid
		r["code"] = a.Code
		r["created"] = a.Created
		r["used"] = a.Used
		r["start"] = a.Start
		r["end"] = a.End
		r["disabled"] = a.Disabled
		r["role_ids"] = a.RoleIds
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "uid":
			r["uid"] = a.Uid
		case "recv_uid":
			r["recv_uid"] = a.RecvUid
		case "code":
			r["code"] = a.Code
		case "created":
			r["created"] = a.Created
		case "used":
			r["used"] = a.Used
		case "start":
			r["start"] = a.Start
		case "end":
			r["end"] = a.End
		case "disabled":
			r["disabled"] = a.Disabled
		case "role_ids":
			r["role_ids"] = a.RoleIds
		}
	}
	return r
}

func (a *NgingCodeInvitation) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *NgingCodeInvitation) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *NgingCodeInvitation) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *NgingCodeInvitation) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *NgingCodeInvitation) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *NgingCodeInvitation) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *NgingCodeInvitation) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
